project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!*-student.qmd"

website:
  page-navigation: true
  title: "Research-Based Practices for Integrating Pair Programming in the Classroom"
  description: "Materials for USCOTS 2025 breakout session on pair programming"
  site-url: "https://jcanner.github.io/uscots-breakout-pair-programming"
  repo-url: https://github.com/jcanner/uscots-breakout-pair-programming
  repo-actions: [issue]

  navbar:
    background: primary
    search: true
    title: false
    left:
       - href: index.qmd
         text: Overview
       - href: bios.qmd
         text: Presenters
       - href: presentation/breakout-pair-programming-slides.qmd
         text: Slides
         target: _blank
       - href: group-tasks/pair-programming-norms.qmd
         text: "Peer Programming Protocol"
       - text: Breakout Session Activities
         menu:
            - href: group-tasks/week-1/broken-circles.qmd
              text: "Broken Circles"
            - href: group-tasks/week-4/pa-3-ggplot.qmd
              text: "ggplot2 Peer Activity"

    right: 
      - icon: github
        href: https://github.com/jcanner/uscots-breakout-pair-programming
      
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Allison Theobold & Judith Canner"
    background: "#D9E3E4"

format:
  html:
    theme: 
      - cosmo
      - style.scss
    toc: true
    df-print: paged

execute:
  freeze: auto